# Generated by Django 5.0.7 on 2024-08-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
    ]
