# Generated by Django 5.0.7 on 2024-08-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_courseinstructor_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
