# Generated by Django 5.0.7 on 2024-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
