# Generated by Django 5.0.7 on 2024-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.IntegerField(default=0),
        ),
    ]
