# Generated by Django 5.0.7 on 2024-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_blog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isLogin',
            field=models.BooleanField(default=False),
        ),
    ]
