# Generated by Django 5.0.7 on 2024-08-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_enrollment_courseinstructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstructor',
            options={'verbose_name': 'CourseInstructor', 'verbose_name_plural': 'Assign teacher to course'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Assign Students to course'},
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
