# Generated by Django 5.0.7 on 2024-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaContent',
            fields=[
                ('content_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=50)),
                ('content_data', models.BinaryField()),
            ],
            options={
                'db_table': 'multimedia_content',
                'managed': False,
            },
        ),
    ]
