# Generated by Django 5.0.7 on 2024-08-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_multimediacontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultimediaContent',
        ),
    ]
